[package]
name = "linear-tui"
edition.workspace = true
license.workspace = true
version.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = "1.0"
linear-core = { path = "../linear-core" }
